language : java
install :
    - git clone https://github.com/PFGimenez/dependency-injector.git --depth 1
    - cd dependency-injector
    - mvn install
    - cd ../core
script :
    - mvn install
    - cd ../example
    - ant
jdk : oraclejdk8
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
    email : false
