language : java
script :
    - cd core && ant
    - cd ../example && ant
    - java -cp bin/:../core/config.jar Example
jdk : oraclejdk8
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
